# Generated by Django 5.0.3 on 2024-03-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
    ]
