# Generated by Django 5.0.3 on 2024-03-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_auto_20240324_0908"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="score",
            field=models.IntegerField(default=77),
        ),
    ]
