# Generated by Django 5.0.3 on 2024-03-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_alter_useractivitylog_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="score",
            field=models.IntegerField(),
        ),
    ]
